part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const ALLSERVICES = _Paths.ALLSERVICES;
  static const SPA = _Paths.SPA;
  static const RESTURANT = _Paths.RESTURANT;
  static const HALLS = _Paths.HALLS;
  static const CARS = _Paths.CARS;
  static const carsCategory = _Paths.carsCategory;
  static const carsOrder = _Paths.carsOrder;
  static const HOUSE_KEEPING = _Paths.HOUSE_KEEPING;
  static const ROOMS = _Paths.ROOMS;
  static const POLMAN = _Paths.POLMAN;
  static const SPASEARCHPAGE = _Paths.SPA_SEARCH_PAGE;
  static const SPACITY = _Paths.SPA_CITY;
  static const SPAHOTEL = _Paths.SPA_HOTEL;
  static const SPADETAILS = _Paths.SPA_DETAILS;
  static const HOUSEKEEPING_SERVICES = _Paths.HOUSEKEEPING_SERVICES;
  static const HOUSEKEEPING_RESERVATION = _Paths.HOUSEKEEPING_RESERVATION;
  static const HALLS_SEARCH = _Paths.HALLS_SEARCH;
  static const CITY_HALLS = _Paths.CITY_HALLS;
  static const HALL_DETAILS = _Paths.HALL_DETAILS;
  static const HOTEL_HALLS = _Paths.HOTEL_HALLS;
  static const HALL_RESERVATION = _Paths.HALL_RESERVATION;
  static const ROOM_RESERVATION = _Paths.ROOM_RESERVATION;
  static const HALL_CALENDER = _Paths.HALL_CALENDER;
  static const ROOM_SEARCH = _Paths.ROOM_SEARCH;
  static const CITY_ROOM_SEARCH_FILTER = _Paths.CITY_ROOM_SEARCH_FILTER;
  static const HOTEL_ROOM_SEARCH_FILTER = _Paths.HOTEl_ROOM_SEARCH_FILTER;
  static const CITY_ROOMS = _Paths.CITY_ROOMS;
  static const HOTEL_ROOMS = _Paths.HOTEL_ROOMS;
  static const ROOM_DETAIL = _Paths.ROOM_DETAIL;
  static const FOOD_SECTION = _Paths.FOOD_SECTION;
  static const FOOD_ITEM = _Paths.FOOD_ITEM;
  static const FOOD_CART = _Paths.FOOD_CART;
  static const HALLS_SEARCH_FILTER = _Paths.HALLS_SEARCH_FILTER;
  static const HALLS_SEARCH_HOTEL_FILTER = _Paths.HALLS_SEARCH_HOTEL_FILTER;
  static const FORGET_PASSWORD = _Paths.FORGETPASSWORD ;
  static const HOTEL_SEARCH_FOR_SERVICES = _Paths.HOTEL_SEARCH_FOR_SERVICES ;
  static const HOTEL_SEARCH_SEARCH_PAGE = _Paths.HOTEL_SEARCH_SEARCH_PAGE ;
  static const MY_ACCOUNT = _Paths.MY_ACCOUNT ;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const FORGETPASSWORD = '/forgetPassword';
  static const ALLSERVICES = '/allservices';
  static const SPA = '/spa';
  static const RESTURANT = '/resturant';
  static const HALLS = '/halls';
  static const CARS = '/cars';
  static const carsCategory = '/carsCategory';
  static const carsOrder = '/carsOrder';
  static const HOUSE_KEEPING = '/house-keeping';
  static const ROOMS = '/rooms';
  static const POLMAN = '/polman';
  static const SPA_SEARCH_PAGE = '/spa-search-page';
  static const SPA_CITY = '/spa-city';
  static const SPA_HOTEL = '/spa-hotel';
  static const SPA_DETAILS = '/spa-details';
  static const HOUSEKEEPING_SERVICES = '/housekeeping-services';
  static const HOUSEKEEPING_RESERVATION = '/housekeeping-reservation';
  static const FOOD_SECTION = '/food-section';
  static const FOOD_ITEM = '/food-item';
  static const HALLS_SEARCH = '/halls-search';
  static const CITY_HALLS = '/city-halls';
  static const HALL_DETAILS = '/halls-details';
  static const FOOD_CART = '/food-cart';
  static const HALL_RESERVATION = '/hall-reservation';
  static const ROOM_RESERVATION = '/room-reservation';
  static const HALL_CALENDER = '/hall-calender';
  static const ROOM_SEARCH = '/rooms-search';
  static const CITY_ROOM_SEARCH_FILTER = '/city-rooms-search-filter';
  static const HOTEl_ROOM_SEARCH_FILTER = '/hotel-city-rooms-search-filter';
  static const CITY_ROOMS = '/city-rooms';
  static const HOTEL_ROOMS = '/hotel-rooms';
  static const ROOM_DETAIL = '/rooms-detail';
  static const HALLS_SEARCH_FILTER = '/halls-search-filter';
  static const HALLS_SEARCH_HOTEL_FILTER = '/halls-search-hotel-filter';
  static const HOTEL_HALLS = '/hotel-halls';
  static const HOTEL_SEARCH_FOR_SERVICES = '/hotel_search_services';
  static const HOTEL_SEARCH_SEARCH_PAGE = '/hotel_search_search_page';
  static const MY_ACCOUNT = '/myAccount';

}
